spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://rm-wz97x9w4mi222h99q5o.mysql.rds.aliyuncs.com:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Black123!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true